### ISSUE TITLE
Why not add to oh-my-zsh?

### ISSUE THREAD

**Issue by alanhogan** [maverick2000/zsh2000#1]
Your README implies this theme doesn’t come with oh-my-zsh, unlike the 120+ that currently do. If you haven't considered submitting it (with a nice description mentioning this and how it's like agnoster but configurable), that might be a great idea :)

**Comment by consolemaverick** [comment]
and 5 years later I finally move on this. While oh-my-zsh doesn't accept adding any more themes I did add it to here https://github.com/ohmyzsh/ohmyzsh/wiki/External-themes
