### ISSUE TITLE
too many levels of symbolic links

### ISSUE THREAD

**Issue by hakkikonu** [maverick2000/zsh2000#4]
i followed install steps,
changed zsh theme name from config file
restarted terminal

then
too many levels of symbolic links

/Users/xx/.oh-my-zsh/oh-my-zsh.sh:source:128: too many levels of symbolic links: /Users/xx/.oh-my-zsh/themes/zsh2000.zsh-theme

and theme not working.

**Comment by MyaLongmire** [comment]
I have the same issue

**Comment by MyaLongmire** [comment]
@hakkikonu You need to move zsh2000.zsh-theme into the .oh-my-zsh/themes folder

**Comment by hakkikonu** [comment]
@MyaLongmire  thanks : )
