### ISSUE TITLE
parse error near `elif'

### ISSUE THREAD

**Issue by ghost** [maverick2000/zsh2000#5]
I've installed zsh2000 and also changed ` /zshrc`,then when I want to run my terminal I got " `parse error near 'elif'` ".
![image](https://user-images.githubusercontent.com/73482387/103445102-495b1780-4c85-11eb-8dc9-a1ff20cc3b72.png)

**Comment by mehrdad-helmi** [comment]
> I've installed zsh2000 and also changed ` /zshrc`,then when I want to run my terminal I got " `parse error near 'elif'` ".
> ![image](https://user-images.githubusercontent.com/73482387/103445102-495b1780-4c85-11eb-8dc9-a1ff20cc3b72.png)

Duplicate of #

**Comment by ghost** [comment]
The problem was with `end of line sequence` , it should be `LF` but Windows changes it to `CRLF`. for wsl users you have to just open the theme file with some editor (like vsode) and change `end of line sequence` to `LF`.
