### ISSUE TITLE
prompt_rvm:2: command not found: rvm-prompt

### ISSUE THREAD

**Issue by mateusdcc** [maverick2000/zsh2000#7]
prompt_rvm:2: command not found: rvm-promp
![Screenshot_2021-11-04-10-56-43_1366x768](https://user-images.githubusercontent.com/68336493/140445346-f442bd4b-6378-409d-8519-d04376c8cff3.png)
Having this error when doing anything in terminal

**Comment by stop-bullshit** [comment]
export ZSH_2000_DISABLE_RVM='true'
you can add in you .zshrc

**Comment by mateusdcc** [comment]
It worked, thanks!
